#!/bin/sh

# Add $HOME/.scripts and $HOME/.local/bin to $PATH if they are not in there already
[[ ":$PATH:" != *":$HOME/.scripts:"* ]] && export PATH="$HOME/.scripts:$PATH"
[[ ":$PATH:" != *":$HOME/.scripts/wrappers:"* ]] && export PATH="$HOME/.scripts/wrappers:$PATH"
[[ ":$PATH:" != *":$HOME/.local/bin:"* ]] && export PATH="$HOME/.local/bin:$PATH"
[[ ":$PATH:" != *":$HOME/.local/share/cargo/bin:"* ]] && export PATH="$HOME/.local/share/cargo/bin:$PATH"
[[ ":$PATH:" != *":$HOME/.local/share/go/bin:"* ]] && export PATH="$HOME/.local/share/go/bin:$PATH"

# Default programs:
export EDITOR="nvim"
export VISUAL="nvim"
export PAGER="most"
export TERMINAL="alacritty"
export BROWSER="firefox"

# Application configs:
export WALLPAPERS_DIR="/linux-storage/Pictures/Wallpapers"

# Load secret environment variables:
[ -f "$HOME/.config/shell/.envsecrets" ] && source "$HOME/.config/shell/.envsecrets"

# ~/ Clean-up - https://wiki.archlinux.org/title/XDG_Base_Directory:
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

alias yarn="yarn --use-yarnrc $XDG_CONFIG_HOME/yarn/config"
alias nvidia-settings="nvidia-settings --config=$XDG_CONFIG_HOME/nvidia/settings"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"
export PYTHONPYCACHEPREFIX="$XDG_CACHE_HOME/python"
export CALCHISTFILE="$XDG_CACHE_HOME/calc_history"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export PARALLEL_HOME="$XDG_CONFIG_HOME/parallel"
export CUDA_CACHE_PATH="$XDG_CACHE_HOME/nv"
export _JAVA_OPTIONS="-Djava.util.prefs.userRoot=$XDG_CONFIG_HOME/java"
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
#export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority" # This line will break some DMs/dwm I guess.
#export NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch-config"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export LESSHISTFILE="-"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
#export ALSA_CONFIG_PATH="$XDG_CONFIG_HOME/alsa/asoundrc"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export WINEPREFIX="$XDG_DATA_HOME/wineprefixes/default"
#export KODI_DATA="$XDG_DATA_HOME/kodi"
#export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export ANDROID_SDK_HOME="$XDG_CONFIG_HOME/android"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export GOPATH="$XDG_DATA_HOME/go"
#export ANSIBLE_CONFIG="$XDG_CONFIG_HOME/ansible/ansible.cfg"
#export UNISON="$XDG_DATA_HOME/unison"
export HISTFILE="$XDG_CONFIG_HOME/shell/history"
export WEECHAT_HOME="$XDG_CONFIG_HOME/weechat"
#export MBSYNCRC="$XDG_CONFIG_HOME/mbsync/config"
#export ELECTRUMDIR="$XDG_DATA_HOME/electrum"
