#!/bin/sh
# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will still be sourced.

# Load shell environment variables
[ -f "$HOME/.config/shell/envrc" ] && source "$HOME/.config/shell/envrc"

#polychromatic-cli -d mouse --dpi 1500                                   # Change the dpi for my Razer mouse
#polychromatic-cli -d mouse -c "#ff0000" -o static                      # Change the color of my Razer mouse
#checkupdates > $XDG_CACHE_HOME/updates.txt &                            # Generate updates info for later use in slstatus
#ntfy subscribe --from-config &

autostartrc="$XDG_CONFIG_HOME/x11/autostartrc"
while read program; do
    [[ "\#$program" != \#* ]] && pgrep "$program" || "$program" &
done < $autostartrc 2>&1 >/dev/null
